server:
  port: 8070

# 配置连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/svsp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver


# Mybatis的配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.network.api.beans
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    config-location: classpath:mybatis/mybatis-config.xml