server:
  port: 8070

# 配置连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/svsp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: mynewroot
    username: root
    driver-class-name: com.mysql.jdbc.Driver


# Mybatis的配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.network.api.beans
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    config-location: classpath:mybatis/mybatis-config.xml

##Eureka的配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka/ #应该和注册中心监控页面一致
#    instance:
#       instance-id: stuserver-service #修改Eureka上的默认描述


# Dubbo的配置
#dubbo:
#  application:
#    name: stuserver-user-service
#  registry:
#    address: 127.0.0.1:2181
#  scan:
#    base-packages: com.network.api.service
#  protocol:
#    name: dubbo
#    port: 20880

#    host: localhost